// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npcvdjcqyviyzwweirjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wY3ZkamNxeXZpeXp3d2Vpcmp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNzA1ODQsImV4cCI6MjA1NzY0NjU4NH0.-Ic96gK1LQxLUhftpu1irpQaMd1g66DSsHlfID_fpGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);